### ISSUE TITLE
[Fix] 코디네이터 객체가 제거되지 않는 문제 수정

### ISSUE THREAD

**Issue by Hansangjin98** [Nexters/tidify-iOS#194]
### 이슈 유형
- [x] 버그

<br>

### 이슈 내용
**AS-IS**: View가 deinit 되는 상황에도 Coordinator를 제거하는 로직은 없음 
**TO-BE**: Coordinator를 제거하는 로직 추가

**Comment by nil-ian** [comment]
7089b54dff1ddda3966b078cce8b448407728ac1 커밋에 반영 완료
